FROM tomcat:8.0.20-jre8 AS build
WORKDIR /app

FROM tomcat:8.0.20-jre8 AS base
# COPY target/*.war /usr/local/tomcat/webapps/maven-web-app.war
COPY --from=build **/*.war /usr/local/tomcat/webapps/maven-web-app.war
