FROM tomcat:8.0.20-jre8 AS build

# COPY **/*.war /usr/local/tomcat/webapps/maven-web-app.war

COPY /home/runner/work/maven-web-app/maven-web-app/target/maven-web-app.war /usr/local/tomcat/webapps/maven-web-app.war
